<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Table des jetons de réinitialisation de mot de passe.
 *
 * `token_hash` porte l'empreinte SHA-256 du jeton, jamais sa valeur en clair : une
 * base volée ne doit livrer aucun jeton utilisable. L'index unique sert donc à la
 * fois de garde-fou et de chemin de recherche — c'est par l'empreinte qu'on retrouve
 * une demande.
 *
 * `ON DELETE CASCADE` : supprimer un compte doit emporter ses jetons. Les laisser
 * orphelins reviendrait à garder des clés valides pour une porte qui n'existe plus.
 */
final class Version20260802174857 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Jetons de réinitialisation de mot de passe (empreinte, expiration, usage unique).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE password_reset_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_password_reset_token_user ON password_reset_token (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_password_reset_token_hash ON password_reset_token (token_hash)');
        $this->addSql('ALTER TABLE password_reset_token ADD CONSTRAINT FK_6B7BA4B6A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE password_reset_token DROP CONSTRAINT FK_6B7BA4B6A76ED395');
        $this->addSql('DROP TABLE password_reset_token');
    }
}
