<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Phase 2 — file Messenger (transport Doctrine) et dates de publication des mangas.
 *
 * La table `messenger_messages` est créée ici plutôt que par l'`auto_setup` du
 * transport (désactivé dans le DSN) : le schéma reste entièrement décrit par les
 * migrations, y compris en production.
 */
final class Version20260801214516 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table messenger_messages (transport Doctrine) + manga.start_date / manga.end_date';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE manga ADD start_date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE manga ADD end_date DATE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE manga DROP start_date');
        $this->addSql('ALTER TABLE manga DROP end_date');
    }
}
