<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260731210012 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schéma initial manga-stream : user, anime, manga, episode, chapter, genre (+ tables de jointure), favorite, progress, comment, notification, recommendation.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, username VARCHAR(50) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_username ON "user" (username)');
        $this->addSql('CREATE TABLE anime (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, anilist_id INT DEFAULT NULL, title_romaji VARCHAR(255) NOT NULL, title_english VARCHAR(255) DEFAULT NULL, title_native VARCHAR(255) DEFAULT NULL, synopsis TEXT DEFAULT NULL, cover_image VARCHAR(512) DEFAULT NULL, banner_image VARCHAR(512) DEFAULT NULL, episode_count INT DEFAULT NULL, average_score INT DEFAULT NULL, status VARCHAR(32) DEFAULT NULL, season VARCHAR(16) DEFAULT NULL, season_year INT DEFAULT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_anime_season ON anime (season_year, season)');
        $this->addSql('CREATE INDEX idx_anime_status ON anime (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_anime_anilist_id ON anime (anilist_id)');
        $this->addSql('CREATE TABLE anime_genre (anime_id INT NOT NULL, genre_id INT NOT NULL, PRIMARY KEY (anime_id, genre_id))');
        $this->addSql('CREATE INDEX IDX_EFF953C7794BBE89 ON anime_genre (anime_id)');
        $this->addSql('CREATE INDEX IDX_EFF953C74296D31F ON anime_genre (genre_id)');
        $this->addSql('CREATE TABLE chapter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number NUMERIC(8, 2) NOT NULL, title VARCHAR(255) DEFAULT NULL, page_count INT DEFAULT NULL, release_date DATE DEFAULT NULL, read_url VARCHAR(1024) DEFAULT NULL, manga_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F981B52E7B6461 ON chapter (manga_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_chapter_manga_number ON chapter (manga_id, number)');
        $this->addSql('CREATE TABLE comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, anime_id INT DEFAULT NULL, manga_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9474526CA76ED395 ON comment (user_id)');
        $this->addSql('CREATE INDEX IDX_9474526C727ACA70 ON comment (parent_id)');
        $this->addSql('CREATE INDEX idx_comment_anime ON comment (anime_id)');
        $this->addSql('CREATE INDEX idx_comment_manga ON comment (manga_id)');
        $this->addSql('CREATE TABLE episode (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number INT NOT NULL, title VARCHAR(255) DEFAULT NULL, duration INT DEFAULT NULL, air_date DATE DEFAULT NULL, thumbnail VARCHAR(512) DEFAULT NULL, stream_url VARCHAR(1024) DEFAULT NULL, anime_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DDAA1CDA794BBE89 ON episode (anime_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_episode_anime_number ON episode (anime_id, number)');
        $this->addSql('CREATE TABLE favorite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, anime_id INT DEFAULT NULL, manga_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_68C58ED9A76ED395 ON favorite (user_id)');
        $this->addSql('CREATE INDEX IDX_68C58ED9794BBE89 ON favorite (anime_id)');
        $this->addSql('CREATE INDEX IDX_68C58ED97B6461 ON favorite (manga_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_favorite_user_anime ON favorite (user_id, anime_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_favorite_user_manga ON favorite (user_id, manga_id)');
        $this->addSql('CREATE TABLE genre (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_genre_name ON genre (name)');
        $this->addSql('CREATE UNIQUE INDEX uniq_genre_slug ON genre (slug)');
        $this->addSql('CREATE TABLE manga (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, anilist_id INT DEFAULT NULL, title_romaji VARCHAR(255) NOT NULL, title_english VARCHAR(255) DEFAULT NULL, title_native VARCHAR(255) DEFAULT NULL, synopsis TEXT DEFAULT NULL, cover_image VARCHAR(512) DEFAULT NULL, banner_image VARCHAR(512) DEFAULT NULL, chapter_count INT DEFAULT NULL, volume_count INT DEFAULT NULL, average_score INT DEFAULT NULL, status VARCHAR(32) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_manga_status ON manga (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_manga_anilist_id ON manga (anilist_id)');
        $this->addSql('CREATE TABLE manga_genre (manga_id INT NOT NULL, genre_id INT NOT NULL, PRIMARY KEY (manga_id, genre_id))');
        $this->addSql('CREATE INDEX IDX_1506CF9F7B6461 ON manga_genre (manga_id)');
        $this->addSql('CREATE INDEX IDX_1506CF9F4296D31F ON manga_genre (genre_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(32) NOT NULL, payload JSON NOT NULL, is_read BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
        $this->addSql('CREATE INDEX idx_notification_user_read ON notification (user_id, is_read)');
        $this->addSql('CREATE TABLE progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, current_episode INT DEFAULT NULL, current_chapter NUMERIC(8, 2) DEFAULT NULL, status VARCHAR(16) NOT NULL, score INT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, anime_id INT DEFAULT NULL, manga_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2201F246A76ED395 ON progress (user_id)');
        $this->addSql('CREATE INDEX IDX_2201F246794BBE89 ON progress (anime_id)');
        $this->addSql('CREATE INDEX IDX_2201F2467B6461 ON progress (manga_id)');
        $this->addSql('CREATE INDEX idx_progress_status ON progress (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_progress_user_anime ON progress (user_id, anime_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_progress_user_manga ON progress (user_id, manga_id)');
        $this->addSql('CREATE TABLE recommendation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score DOUBLE PRECISION NOT NULL, reason JSON NOT NULL, generated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, anime_id INT DEFAULT NULL, manga_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_433224D2A76ED395 ON recommendation (user_id)');
        $this->addSql('CREATE INDEX IDX_433224D2794BBE89 ON recommendation (anime_id)');
        $this->addSql('CREATE INDEX IDX_433224D27B6461 ON recommendation (manga_id)');
        $this->addSql('CREATE INDEX idx_recommendation_user_score ON recommendation (user_id, score)');
        $this->addSql('ALTER TABLE anime_genre ADD CONSTRAINT FK_EFF953C7794BBE89 FOREIGN KEY (anime_id) REFERENCES anime (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE anime_genre ADD CONSTRAINT FK_EFF953C74296D31F FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chapter ADD CONSTRAINT FK_F981B52E7B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C794BBE89 FOREIGN KEY (anime_id) REFERENCES anime (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C7B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C727ACA70 FOREIGN KEY (parent_id) REFERENCES comment (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE episode ADD CONSTRAINT FK_DDAA1CDA794BBE89 FOREIGN KEY (anime_id) REFERENCES anime (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED9794BBE89 FOREIGN KEY (anime_id) REFERENCES anime (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED97B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE manga_genre ADD CONSTRAINT FK_1506CF9F7B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE manga_genre ADD CONSTRAINT FK_1506CF9F4296D31F FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE progress ADD CONSTRAINT FK_2201F246A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE progress ADD CONSTRAINT FK_2201F246794BBE89 FOREIGN KEY (anime_id) REFERENCES anime (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE progress ADD CONSTRAINT FK_2201F2467B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recommendation ADD CONSTRAINT FK_433224D2A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recommendation ADD CONSTRAINT FK_433224D2794BBE89 FOREIGN KEY (anime_id) REFERENCES anime (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recommendation ADD CONSTRAINT FK_433224D27B6461 FOREIGN KEY (manga_id) REFERENCES manga (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE anime_genre DROP CONSTRAINT FK_EFF953C7794BBE89');
        $this->addSql('ALTER TABLE anime_genre DROP CONSTRAINT FK_EFF953C74296D31F');
        $this->addSql('ALTER TABLE chapter DROP CONSTRAINT FK_F981B52E7B6461');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526CA76ED395');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C794BBE89');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C7B6461');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C727ACA70');
        $this->addSql('ALTER TABLE episode DROP CONSTRAINT FK_DDAA1CDA794BBE89');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED9A76ED395');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED9794BBE89');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED97B6461');
        $this->addSql('ALTER TABLE manga_genre DROP CONSTRAINT FK_1506CF9F7B6461');
        $this->addSql('ALTER TABLE manga_genre DROP CONSTRAINT FK_1506CF9F4296D31F');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE progress DROP CONSTRAINT FK_2201F246A76ED395');
        $this->addSql('ALTER TABLE progress DROP CONSTRAINT FK_2201F246794BBE89');
        $this->addSql('ALTER TABLE progress DROP CONSTRAINT FK_2201F2467B6461');
        $this->addSql('ALTER TABLE recommendation DROP CONSTRAINT FK_433224D2A76ED395');
        $this->addSql('ALTER TABLE recommendation DROP CONSTRAINT FK_433224D2794BBE89');
        $this->addSql('ALTER TABLE recommendation DROP CONSTRAINT FK_433224D27B6461');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE anime');
        $this->addSql('DROP TABLE anime_genre');
        $this->addSql('DROP TABLE chapter');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE episode');
        $this->addSql('DROP TABLE favorite');
        $this->addSql('DROP TABLE genre');
        $this->addSql('DROP TABLE manga');
        $this->addSql('DROP TABLE manga_genre');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE progress');
        $this->addSql('DROP TABLE recommendation');
    }
}
