/**
 * Typed API client.
 *
 * `paths` comes from `src/api/schema.ts`, generated by `npm run generate:api`
 * from the shared contract `docs/openapi.yaml` (API Platform 4).
 *
 * ── Content negotiation ────────────────────────────────────────────────────
 * The backend serves every resource in two flavours:
 *   - `application/ld+json` → JSON-LD / Hydra envelope (`member`, `totalItems`)
 *   - `application/json`    → bare array, no pagination metadata
 *
 * We commit to **application/ld+json**: pagination metadata is required for the
 * catalogue's infinite scroll. That choice is pinned in the type system through
 * the second generic of `createClient`, so `data` is the Hydra shape and never
 * a union of both — and the `Accept` header matches what the types claim.
 */
import createClient, { type Middleware } from 'openapi-fetch'
import type { paths } from './schema'
import { API_BASE_URL } from '../config'
import { getSession, isTokenExpired, notifyUnauthorized, setSession } from '../auth/session'

/** The single media type this app speaks. Keep the header and the generic in sync. */
export const MEDIA_TYPE = 'application/ld+json'

export const apiClient = createClient<paths, typeof MEDIA_TYPE>({
  baseUrl: API_BASE_URL,
  headers: { Accept: MEDIA_TYPE },
})

/**
 * Second client, pinned to plain `application/json`, for the handful of
 * operations the contract does **not** serve as JSON-LD.
 *
 * `POST /api/login` is the only one today: it declares `application/json`
 * exclusively, so asking `apiClient` for it yields `never` — the media type it
 * is pinned to simply is not in that operation's response map.
 *
 * It deliberately carries **no auth middleware**: login must never be able to
 * trigger the global "session expired" logout, and it has no token to send.
 */
export const jsonApiClient = createClient<paths, 'application/json'>({
  baseUrl: API_BASE_URL,
  headers: { Accept: 'application/json' },
})

/**
 * Auth middleware — the single place where the JWT enters the request, and the
 * single place where a 401 is turned into a logout. No call site knows about
 * authentication.
 *
 * Two guards keep the "expired token" path from looping:
 *
 *  1. `onRequest` refuses to send an already-expired token: it clears the
 *     session locally instead. So we do not even generate the 401.
 *  2. `onResponse` only reacts when the request actually carried a token, and
 *     `notifyUnauthorized()` is itself idempotent (it no-ops once the session
 *     is gone). A burst of parallel 401s therefore triggers exactly one logout.
 *
 * `AUTH_PATHS` is belt-and-braces: those requests normally carry no token, so
 * guard 2 already skips them, but an authenticated user re-submitting the
 * login form must never be logged out by their own typo.
 */
const AUTH_PATHS = ['/api/login', '/api/register']

const authMiddleware: Middleware = {
  onRequest({ request }) {
    const session = getSession()
    if (!session) return request

    if (isTokenExpired(session.token)) {
      // Guard 1: locally expired. Drop it silently; the caller will simply get
      // the anonymous response. `setSession` (not `notifyUnauthorized`) because
      // this is not a server rejection and needs no redirect of its own —
      // `AuthProvider` re-renders and the protected routes bounce naturally.
      setSession(null)
      return request
    }

    request.headers.set('Authorization', `Bearer ${session.token}`)
    return request
  },

  onResponse({ request, response }) {
    if (response.status !== 401) return response
    // Guard 2: only an *authenticated* request that got rejected means the
    // token died. A 401 on an anonymous request is just a protected endpoint.
    if (!request.headers.has('Authorization')) return response
    if (AUTH_PATHS.some((path) => new URL(request.url).pathname.endsWith(path))) return response

    notifyUnauthorized()
    return response
  },
}

apiClient.use(authMiddleware)

/**
 * Une violation de validation, telle que le contrat la décrit dans
 * `ConstraintViolation` (`422`). `propertyPath` est le champ visé
 * ("currentEpisode"), `message` la phrase produite par le validateur Symfony.
 */
export type Violation = { propertyPath: string; message: string }

/** Thrown when the API answers with a non-2xx status. */
export class ApiError extends Error {
  readonly status?: number
  /**
   * Violations d'un 422, vide sinon.
   *
   * Elles sont conservées à part du `message` parce qu'un formulaire veut les
   * rattacher à leurs champs, alors qu'un affichage générique se contente du
   * message agrégé. Sans ça, le seul recours serait de re-parser `detail`,
   * qui n'est qu'une concaténation « champ: message ».
   */
  readonly violations: Violation[]

  constructor(message: string, status?: number, violations: Violation[] = []) {
    super(message)
    this.name = 'ApiError'
    this.status = status
    this.violations = violations
  }
}

/**
 * Extrait les violations d'un corps d'erreur 422.
 *
 * Défensif de bout en bout : le corps vient du réseau, `violations` peut être
 * absent, ne pas être un tableau, ou contenir des entrées incomplètes. Une
 * entrée sans `message` exploitable est écartée plutôt que rendue « undefined ».
 */
function readViolations(error: unknown): Violation[] {
  if (typeof error !== 'object' || error === null || !('violations' in error)) return []
  const raw = (error as { violations: unknown }).violations
  if (!Array.isArray(raw)) return []

  return raw.flatMap((item): Violation[] => {
    if (typeof item !== 'object' || item === null) return []
    const { propertyPath, message } = item as { propertyPath?: unknown; message?: unknown }
    if (typeof message !== 'string' || message.trim() === '') return []
    return [
      {
        propertyPath: typeof propertyPath === 'string' ? propertyPath : '',
        message: message.trim(),
      },
    ]
  })
}

/**
 * Turns an API Platform `detail` into something safe to put in front of a user.
 *
 * The backend leaks raw Doctrine/PostgreSQL errors on some failures — a
 * duplicate favourite currently answers **500** with the full
 * `SQLSTATE[23505] … duplicate key value violates unique constraint` message
 * and a stack trace (observed against the running backend, reported upstream).
 * Rendering that verbatim would be both unreadable and an information leak, so
 * the known cases are translated and anything else DB-shaped is genericised.
 * The original stays in the console for whoever is debugging.
 */
function humanizeDetail(detail: string, status: number): string {
  if (/duplicate key|unique constraint|already exists/i.test(detail)) {
    return 'Cet élément existe déjà.'
  }
  if (/SQLSTATE|An exception occurred while executing/i.test(detail)) {
    console.warn('[api] Erreur base de données renvoyée telle quelle par le backend :', detail)
    return `Le serveur a rencontré une erreur (${status}).`
  }
  // Long details are almost always stack traces or dumps, not user-facing prose.
  return detail.length > 300 ? `Le serveur a rencontré une erreur (${status}).` : detail
}

/**
 * Unwraps an `openapi-fetch` result, throwing on error so React Query can
 * handle failures through its normal error state. API Platform returns RFC 7807
 * style errors, whose human-readable field is `detail`.
 */
export function unwrap<T>(result: { data?: T; error?: unknown; response: Response }): T {
  if (result.error || result.data === undefined) {
    const { status } = result.response
    const violations = readViolations(result.error)
    const raw =
      typeof result.error === 'object' && result.error !== null && 'detail' in result.error
        ? String((result.error as { detail: unknown }).detail)
        : null

    // Sur un 422, les violations sont la formulation la plus lisible : le
    // `detail` d'API Platform les concatène avec leur chemin de propriété
    // ("currentEpisode: L'épisode ne peut pas dépasser…"), ce qui expose un nom
    // de champ interne à l'utilisateur.
    const message =
      violations.length > 0
        ? violations.map((violation) => violation.message).join(' ')
        : raw
          ? humanizeDetail(raw, status)
          : `La requête a échoué (${status}).`

    throw new ApiError(message, status, violations)
  }
  return result.data
}
