/**
 * Typed API client.
 *
 * `paths` comes from `src/api/schema.ts`, generated by `npm run generate:api`
 * from the shared contract `docs/openapi.yaml` (API Platform 4).
 *
 * ── Content negotiation ────────────────────────────────────────────────────
 * The backend serves every resource in two flavours:
 *   - `application/ld+json` → JSON-LD / Hydra envelope (`member`, `totalItems`)
 *   - `application/json`    → bare array, no pagination metadata
 *
 * We commit to **application/ld+json**: pagination metadata is required for the
 * catalogue's infinite scroll. That choice is pinned in the type system through
 * the second generic of `createClient`, so `data` is the Hydra shape and never
 * a union of both — and the `Accept` header matches what the types claim.
 */
import createClient, { type Middleware } from 'openapi-fetch'
import type { paths } from './schema'
import { API_BASE_URL } from '../config'

/** The single media type this app speaks. Keep the header and the generic in sync. */
export const MEDIA_TYPE = 'application/ld+json'

export const apiClient = createClient<paths, typeof MEDIA_TYPE>({
  baseUrl: API_BASE_URL,
  headers: { Accept: MEDIA_TYPE },
})

/**
 * Auth injection point (phase 2).
 *
 * Phase 1 endpoints are all public — the contract declares no `securitySchemes`
 * yet. When JWT lands, the only change needed is to read the token here and set
 * the header; every call site stays untouched.
 */
const authMiddleware: Middleware = {
  onRequest({ request }) {
    // eslint-disable-next-line no-constant-condition
    const token: string | null = null // ← phase 2: read from the auth store
    if (token) {
      request.headers.set('Authorization', `Bearer ${token}`)
    }
    return request
  },
}

apiClient.use(authMiddleware)

/** Thrown when the API answers with a non-2xx status. */
export class ApiError extends Error {
  readonly status?: number

  constructor(message: string, status?: number) {
    super(message)
    this.name = 'ApiError'
    this.status = status
  }
}

/**
 * Unwraps an `openapi-fetch` result, throwing on error so React Query can
 * handle failures through its normal error state. API Platform returns RFC 7807
 * style errors, whose human-readable field is `detail`.
 */
export function unwrap<T>(result: { data?: T; error?: unknown; response: Response }): T {
  if (result.error || result.data === undefined) {
    const detail =
      typeof result.error === 'object' && result.error !== null && 'detail' in result.error
        ? String((result.error as { detail: unknown }).detail)
        : `Request failed with status ${result.response.status}`
    throw new ApiError(detail, result.response.status)
  }
  return result.data
}
